### PR TITLE
chroma.js is used for computing the color of the graphs

### PR DESCRIPTION
**Pull request by carmelopellegrino**
chroma.js is used for computing the color of the graphs, so it is easy to extend the number of independent colors and change the palette.

### CODE REVIEW

**Comment by tamasgal** [comment]
Hehe, yea Javascript is pretty funny. It's even more fun that there are so many different design concepts to manufacture classes etc. Quite confusing at the beginning…

**Comment by tamasgal** [comment]
It's nice, however we should consider shuffling the colors, since now the differences are quite subtle ; )

**Comment by carmelopellegrino** [comment]
Yes! Before this I tried to pass to the scale object this function:
Math.cos(10 / (i + 0.1))
just to shuffle the colours, but the problem was that this function has asymptotic convergence and the colours for i > 35 was just undistinguishable... :-S

I think that the best solution is to set different colours only on multi-plot graphs, possibly providing to the user a way to set it!

**Comment by tamasgal** [comment]
Yes, custom colours would be the final solution. At the time I'm quite busy with other projects but I'll implement it soon!

**Pull request merged**
